---
title: "[tpetzoldt](https://github.com/tpetzoldt)'s open source projects"
output:
  html_document
---


This page serves additional documentation of some of my Github and other source code projects. Most of the packages and code snippets were written in the [**R** programming language](https://www.r-project.org) for statistical computing.


## Github projects

| Repository (Source Code) | Type | Release | Author/(Maintainer) | Documentation |
|:--------------------------------------------------------|---------|------|--------|:--------------|
| [antibioticR](https://github.com/tpetzoldt/antibioticR) |R package | alpha  |[tpetzoldt](https://github.com/tpetzoldt)| [Introduction](antibioticR/articles/Introduction.html)|
| [growthrates](https://github.com/tpetzoldt/growthrates) |R package | [CRAN](https://cran.r-project.org/package=growthrates) | [tpetzoldt](https://github.com/tpetzoldt)|  [01 Introduction](growthrates/doc/Introduction.html), [02 User-defined models](growthrates/doc/User_models.html)|
| [FAmle](https://github.com/tpetzoldt/FAmle) |R package | [CRAN](https://cran.r-project.org/package=FAmle) | F.Aucoin / ([tpetzoldt](https://github.com/tpetzoldt))| [CRAN](https://cran.r-project.org/package=FAmle) |
| [FAdist](https://github.com/tpetzoldt/FAdist) |R package | [CRAN](https://cran.r-project.org/package=FAdist) | F.Aucoin / ([tpetzoldt](https://github.com/tpetzoldt))| [CRAN](https://cran.r-project.org/package=FAmle) |
| [dynamic-R-models](https://github.com/tpetzoldt/dynamic-R-models) |code snippets | [Github](https://github.com/tpetzoldt/dynamic-R-models)    |[tpetzoldt](https://github.com/tpetzoldt)| [Github](https://github.com/tpetzoldt/dynamic-R-models)  |
| - chemostat-ODE | code snippets | | | - [chemostat-ode](chemostat/chemostat-ode.html) |
| - chemostat-IBM | code snippets | | | - [chemostat-ibm](chemostat/chemostat-ibm.html) |
| - forcing functions and events | code snippets | | | - [deSolve-forcing](deSolve-forcing/deSolve-forcing.html) |
| - dynamic models in compiled code | code snippets | | | - [deSolve-compiled](deSolve-compiled/deSolve-compiled.html) |
| - dynamic models with shiny | code snippets | | | - [deSolve-shiny](deSolve-shiny/deSolve-shiny.html) |
| - stoichiometry-matrix ODE models with rodeo | code snippets | | | - [deSolve-rodeo](deSolve-rodeo/rodeo-lv3.html) |
| [Elements of Statistics with R](https://github.com/tpetzoldt/elements) |teaching | alpha  |[tpetzoldt](https://github.com/tpetzoldt/)| [Slides, Tutorials](elements/)|
| [growthlab](https://github.com/tpetzoldt/growthlab) |teaching | alpha  |[tpetzoldt](https://github.com/tpetzoldt)| [Digitally controlled growth experiments](https://tpetzoldt.github.io/growthlab/)|
| | | | | |

## Other repositories

**Note:** some of my other collaborative **R** projects are hosted on [R-Forge](https://r-forge.r-project.org/users/petzoldt/). 

| R package | Author | Release | Repository | More |
|---------|---------|---------|----------|-------------|
| simecol | Petzoldt        | [CRAN](https://cran.r-project.org/package=simecol) | [R-Forge](https://r-forge.r-project.org/projects/simecol/) | [Homepage](http://simecol.r-forge.r-project.org) |
| deSolve | Soetaert, Petzoldt and Setzer | [CRAN](https://cran.r-project.org/package=deSolve) | [R-Forge](https://r-forge.r-project.org/projects/desolve/) | [Homepage](http://desolve.r-forge.r-project.org) |
| FME     | Soetaert and Petzoldt | [CRAN](https://cran.r-project.org/package=FME) | [R-Forge](https://r-forge.r-project.org/projects/fme/) | [Docs](https://cran.r-project.org/package=FME) |
| marelac | Soetaert et al. | [CRAN](https://cran.r-project.org/package=marelac) | [R-Forge](https://r-forge.r-project.org/projects/marelac/) | [Docs](https://cran.r-project.org/package=marelac) |
| qualV   | van den Boogaart, Rost and Petzoldt  | [CRAN](https://cran.r-project.org/package=qualV)   | [R-Forge](https://r-forge.r-project.org/projects/qualv/) | [Docs](https://cran.r-project.org/package=qualV) |
| cardidates   | Rolinski, Sachse and Petzoldt  | [CRAN](https://cran.r-project.org/package=cardidates)   | [R-Forge](https://r-forge.r-project.org/projects/cardidates/) | [Docs](https://cran.r-project.org/package=cardidates) |
| rLimnoLab | Petzoldt et al.      |        alpha                                   | [R-Forge](https://r-forge.r-project.org/projects/rlimnolab/) | [Homepage](http://rlimnolab.r-forge.r-project.org) |


## About the author

* List of my Github repositories see https://github.com/tpetzoldt?tab=repositories
* List of my R-Forge repositories see https://r-forge.r-project.org/users/petzoldt/
* ResearchGate profile: https://www.researchgate.net/profile/Thomas_Petzoldt
* Homepage of the author: https://tu-dresden.de/Members/thomas.petzoldt

----

**Copyright and original author:** [tpetzoldt](https://github.com/tpetzoldt), `r Sys.Date()`
